# Generated by Django 4.1.7 on 2023-02-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leito', models.CharField(choices=[('leito1', 'leito1'), ('leito2', 'leito2'), ('leito3', 'leito3')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
