# Generated by Django 4.1.7 on 2023-02-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0002_dataatual'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeitosGraficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leito', models.CharField(choices=[('A877', 'A877'), ('leito2', 'leito2'), ('leito3', 'leito3')], max_length=200)),
            ],
        ),
    ]
