# Generated by Django 4.1.7 on 2023-02-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0003_leitosgraficos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leitosgraficos',
            old_name='leito',
            new_name='leitos_graficos_neuro',
        ),
    ]
