# Generated by Django 4.1.7 on 2023-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodeldatehj',
            name='col3',
            field=models.DateField(),
        ),
    ]
