# Generated by Django 4.1.7 on 2023-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0002_rename_customuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserCreationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_de_login', models.TextField(max_length=50)),
            ],
        ),
    ]
