# Generated by Django 4.1.7 on 2023-02-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0003_myusercreationform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusercreationform',
            name='dados_de_login',
        ),
    ]
