# Generated by Django 4.1.7 on 2023-02-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0004_remove_myusercreationform_dados_de_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoBtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
