# Generated by Django 4.1.7 on 2023-02-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(max_length=50)),
                ('col2', models.IntegerField()),
                ('col3', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
