# Generated by Django 4.1.7 on 2023-02-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='col2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='col3',
        ),
    ]
