# Generated by Django 4.1.7 on 2023-02-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0002_remove_mymodel_col2_remove_mymodel_col3'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModelDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col2', models.DateTimeField()),
            ],
        ),
    ]
