# Generated by Django 4.1.7 on 2023-02-22 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deteriora', '0003_mymodeldate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodeldate',
            name='col2',
        ),
        migrations.AddField(
            model_name='mymodeldate',
            name='col3',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
